server:
    port: 8090

spring:
    jpa:
        generate-ddl: true
        database: postgresql
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                # show_sql: true
                # format_sql: true
        hibernate:
            ddl-auto: update
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres
        username:
        password:

    # MULTIPART (MultipartProperties)
    # Enable multipart uploads
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 200MB
            max-request-size: 215MB
    sql:
        init:
            schema-locations: classpath:init.sql
            mode: always


# json web token properties
app:
    jwtSecret: secretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkey

# cookie
cookie:
    domain: localhost

## File Storage Properties
file:
    upload-dir: ../teamlog-front-end/public/storage
    stored-path-prefix: /storage

# Swagger
springdoc:
    swagger-ui:
        path: /swagger-ui.html
        groups-order: DESC
        operationsSorter: method
        disable-swagger-default-url: true
        display-request-duration: true

    api-docs:
        path: /api-docs

    show-actuator: true

    default-consumes-media-type: application/json
    default-produces-media-type: application/json
    paths-to-match:
        - /api/**

decorator:
    datasource:
        p6spy:
            enable-logging: true # SQL 로그 찍기, 운영 환경에서는 false로 설정하기