server:
    port: 8090

spring:
    jpa:
        generate-ddl: true
        database: postgresql
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                # show_sql: true
                # format_sql: true
        hibernate:
            ddl-auto: update
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres
        username: teamlog
        password: 1234

    # MULTIPART (MultipartProperties)
    # Enable multipart uploads
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 200MB
            max-request-size: 215MB


# json web token properties
app:
    jwtSecret: secretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkey

# cookie
cookie:
    domain: localhost

## File Storage Properties
file:
    upload-dir: ../teamlog-front-end/public/storage
    stored-path-prefix: /storage

# Swagger
springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /
        disable-swagger-default-url: true
        display-request-duration: true
        operations-sorter: alpha


    default-consumes-media-type: application/json
    default-produces-media-type: application/json

decorator:
    datasource:
        p6spy:
            enable-logging: true # SQL 로그 찍기, 운영 환경에서는 false로 설정하기